[package]
name = "remembrall"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
reqwest = { version = "0.13.1", features = ["blocking", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
